services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: mk
      POSTGRES_PASSWORD: mk
      POSTGRES_DB: mkdb
      TZ: Asia/Seoul
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mk -d mkdb || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  pgdata: